apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-1.0
  namespace: order
spec:
  selector:
    matchLabels:
      app: order
      version: "1.0"
  template:
    metadata:
      labels:
        app: order
        version: "1.0"
    spec:
      containers:
      - name: order
        image: yoonjeong/snackbar-order:1.0
        resources:
          requests:
            memory: "32Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 8080
        env:
          - name: PORT
            valueFrom:
              configMapKeyRef:
                key: ORDER_HTTP_PORT
                name: port-config
